services:
  db:
    image: postgres:13
    container_name: postgres_db_node_bassma
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  node:
    image: ${DOCKER_USERNAME}/nodejs_postgres:latest
    container_name: nodejs_app_bassma
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/mydb
      - NODE_ENV=prod
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    command: ["npm", "run", "start"]
    ports:
      - "3027:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bassma.rule=Host(`bassma.soudry-ort.online`)"
      - "traefik.http.routers.bassma.entrypoints=web"
      - "traefik.http.routers.bassma.entrypoints=websecure"
      - "traefik.http.routers.bassma.tls.certresolver=myresolver"
      - "traefik.http.routers.bassma-http.middlewares=redirect-to-https"
    networks:
      - admin_web_traefik

volumes:
  db_data:

networks:
  admin_web_traefik:
    external: true
