name: Dev CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_TOKEN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t ${{ secrets.DOCKER_TOKEN }}/nodejs_postgres:dev .

      - run: docker push ${{ secrets.DOCKER_TOKEN }}/nodejs_postgres:dev

