name: Security Scan

on:
  push:
    branches:
      - security

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t nodejs_postgres:security .

      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - name: Run Trivy scan
        run: trivy image --exit-code 1 --ignore-unfixed --severity HIGH,CRITICAL nodejs_postgres:security
